# services:
#   - type: web
#     name: gbv-backend
#     env: python
#     buildCommand: "cd report_backend && pip install -r ../requirements.txt"
#     startCommand: "cd report_backend && gunicorn report_backend.wsgi:application"
#     envVars:
#       - key: DJANGO_SETTINGS_MODULE
#         value: report_backend.settings
#       - key: SECRET_KEY
#         value: <your-secret-key>
#       - key: DATABASE_URL
#         fromDatabase:
#           name: gbv3-db
#           property: connectionString

# databases:
#   - name: gbv3-db
#     plan: free


services:
  - type: web
    name: gbv-backend
    env: python
    buildCommand: "cd report_backend && pip install -r ../requirements.txt"
    startCommand: "cd report_backend && gunicorn report_backend.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: report_backend.report_backend.settings
      - key: SECRET_KEY
        value: your-secret-key
      - key: DATABASE_URL
        fromDatabase:
          name: gbv3-db
          property: connectionString

databases:
  - name: gbv3-db
    plan: free
