# services:
#   - type: web
#     name: gbv-backend
#     env: python
#     buildCommand: "pip install -r requirements.txt"
#     startCommand: "gunicorn report_backend.wsgi:application"
#     envVars:
#       - key: DJANGO_SETTINGS_MODULE
#         value: report_backend.settings
#       - key: SECRET_KEY
#         value: <your-secret-key>
#       - key: DATABASE_URL
#         fromDatabase:
#           name: gbv3-db
#           property: connectionString
# databases:
#   - name: gbv3-db
#     plan: free


services:
  - type: web
    name: gbv-backend
    env: python
    buildCommand: |
      cd report_backend && 
      pip install -r ../requirements.txt
    startCommand: |
      cd report_backend &&
      python manage.py migrate &&
      gunicorn report_backend.wsgi:application --bind 0.0.0.0:$PORT --pythonpath "/opt/render/project/src/report_backend"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: report_backend.report_backend.deployment_settings
      - key: PYTHONPATH
        value: /opt/render/project/src:/opt/render/project/src/report_backend
      - key: SECRET_KEY
        value: <your-secret-key>
      - key: DISABLE_COLLECTSTATIC
        value: "1"
      - key: DATABASE_URL
        fromDatabase:
          name: gbv3-db
          property: connectionString

databases:
  - name: gbv3-db
    plan: free