# Generated by Django 5.1.1 on 2025-04-18 14:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Sexual Harassment', 'Sexual Harassment'), ('Sexual Assault', 'Sexual Assault'), ('Domestic Violence', 'Domestic Violence'), ('Stalking', 'Stalking'), ('Verbal Abuse', 'Verbal Abuse'), ('Emotional Abuse', 'Emotional Abuse'), ('Other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('gender', models.CharField(blank=True, choices=[('female', 'Female'), ('male', 'Male'), ('other', 'Other')], max_length=10, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('perpetrator_details', models.TextField(blank=True, null=True)),
                ('anonymous', models.BooleanField(default=False)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('evidence', models.FileField(blank=True, null=True, upload_to='evidence/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
