# Generated by Django 5.1.1 on 2025-04-18 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='status',
            field=models.CharField(default='New', max_length=100),
        ),
    ]
