# Generated by Django 5.2 on 2025-07-14 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_availability_psychologistprofile_booking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychologistprofile',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='psychologistprofile',
            name='languages',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='psychologistprofile',
            name='license_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='psychologistprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='psychologistprofile',
            name='therapy_approach',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='psychologistprofile',
            name='years_of_experience',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
