# Generated by Django 5.2 on 2025-07-16 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_psychologistprofile_hourly_rate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='client',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='psychologist',
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='psychologist',
        ),
        migrations.RemoveField(
            model_name='ratecard',
            name='psychologist',
        ),
        migrations.RemoveField(
            model_name='review',
            name='client',
        ),
        migrations.RemoveField(
            model_name='review',
            name='psychologist',
        ),
        migrations.RemoveField(
            model_name='psychologistprofile',
            name='hourly_rate',
        ),
        migrations.RemoveField(
            model_name='psychologistprofile',
            name='id',
        ),
        migrations.RemoveField(
            model_name='psychologistprofile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='psychologistprofile',
            name='specialization',
        ),
        migrations.RemoveField(
            model_name='psychologistprofile',
            name='therapy_approach',
        ),
        migrations.RemoveField(
            model_name='psychologistprofile',
            name='years_of_experience',
        ),
        migrations.AddField(
            model_name='psychologistprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='psychologistprofile',
            name='specializations',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='psychologistprofile',
            name='username',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='psychologistprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='psychologistprofile',
            name='languages',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='psychologistprofile',
            name='license_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='psychologistprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='psychologistprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Availability',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Qualification',
        ),
        migrations.DeleteModel(
            name='RateCard',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
