# Generated by Django 5.2 on 2025-07-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_psychologistavailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='calendar_event_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
