# Generated by Django 5.2 on 2025-07-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_booking_calendar_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychologistprofile',
            name='google_auth_token',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
