# Generated by Django 5.2 on 2025-07-19 18:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0015_booking_client_alter_booking_client_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable'), ('booked', 'Booked')], default='available', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='availability',
            unique_together={('psychologist', 'start', 'end')},
        ),
    ]
