# Generated by Django 5.2 on 2025-07-20 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0017_user_passwordresettoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='PasswordResetToken',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
