# Generated by Django 5.2 on 2025-07-23 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0019_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
