# Generated by Django 5.2 on 2025-07-23 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('reports', '0020_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAuthDetails',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='auth_details', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('token_created_at', models.DateTimeField(blank=True, null=True)),
                ('account_status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('failed_login_attempts', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Authentication Detail',
                'verbose_name_plural': 'User Authentication Details',
            },
        ),
    ]
